apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: e2e-tests-java-quarkus-cssicwle
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/e2e-tests-java-quarkus-cssicwle:273e95e8f89c1b32ccb64f0485265722bb22f1ee
          name: container-image
